// <auto-generated />
using System;
using AirportSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportSystem.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AirportSystem.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightID = 1,
                            ArrivalAirport = "New York JFK",
                            DestinationAirport = "Los Angeles LAX",
                            FlightNumber = "AA100",
                            FlightStatus = 0,
                            Gate = "A12",
                            Time = new DateTime(2025, 9, 13, 14, 39, 23, 318, DateTimeKind.Local).AddTicks(3448)
                        },
                        new
                        {
                            FlightID = 2,
                            ArrivalAirport = "Chicago O'Hare",
                            DestinationAirport = "Miami MIA",
                            FlightNumber = "UA200",
                            FlightStatus = 1,
                            Gate = "B8",
                            Time = new DateTime(2025, 9, 13, 16, 39, 23, 318, DateTimeKind.Local).AddTicks(3470)
                        },
                        new
                        {
                            FlightID = 3,
                            ArrivalAirport = "Atlanta ATL",
                            DestinationAirport = "Seattle SEA",
                            FlightNumber = "DL300",
                            FlightStatus = 3,
                            Gate = "C15",
                            Time = new DateTime(2025, 9, 13, 18, 39, 23, 318, DateTimeKind.Local).AddTicks(3472)
                        },
                        new
                        {
                            FlightID = 4,
                            ArrivalAirport = "Dallas DFW",
                            DestinationAirport = "Denver DEN",
                            FlightNumber = "SW400",
                            FlightStatus = 0,
                            Gate = "D22",
                            Time = new DateTime(2025, 9, 13, 20, 39, 23, 318, DateTimeKind.Local).AddTicks(3474)
                        },
                        new
                        {
                            FlightID = 5,
                            ArrivalAirport = "London LHR",
                            DestinationAirport = "New York JFK",
                            FlightNumber = "BA500",
                            FlightStatus = 1,
                            Gate = "E5",
                            Time = new DateTime(2025, 9, 13, 22, 39, 23, 318, DateTimeKind.Local).AddTicks(3476)
                        },
                        new
                        {
                            FlightID = 6,
                            ArrivalAirport = "Frankfurt FRA",
                            DestinationAirport = "Chicago O'Hare",
                            FlightNumber = "LH600",
                            FlightStatus = 2,
                            Gate = "F12",
                            Time = new DateTime(2025, 9, 14, 0, 39, 23, 318, DateTimeKind.Local).AddTicks(3478)
                        },
                        new
                        {
                            FlightID = 7,
                            ArrivalAirport = "Paris CDG",
                            DestinationAirport = "Los Angeles LAX",
                            FlightNumber = "AF700",
                            FlightStatus = 4,
                            Gate = "G8",
                            Time = new DateTime(2025, 9, 14, 2, 39, 23, 318, DateTimeKind.Local).AddTicks(3479)
                        },
                        new
                        {
                            FlightID = 8,
                            ArrivalAirport = "Tokyo NRT",
                            DestinationAirport = "San Francisco SFO",
                            FlightNumber = "JL800",
                            FlightStatus = 0,
                            Gate = "H3",
                            Time = new DateTime(2025, 9, 14, 4, 39, 23, 318, DateTimeKind.Local).AddTicks(3481)
                        },
                        new
                        {
                            FlightID = 9,
                            ArrivalAirport = "Seoul ICN",
                            DestinationAirport = "New York JFK",
                            FlightNumber = "KE900",
                            FlightStatus = 1,
                            Gate = "I7",
                            Time = new DateTime(2025, 9, 14, 6, 39, 23, 318, DateTimeKind.Local).AddTicks(3483)
                        },
                        new
                        {
                            FlightID = 10,
                            ArrivalAirport = "Singapore SIN",
                            DestinationAirport = "Los Angeles LAX",
                            FlightNumber = "SQ1000",
                            FlightStatus = 3,
                            Gate = "J11",
                            Time = new DateTime(2025, 9, 14, 8, 39, 23, 318, DateTimeKind.Local).AddTicks(3484)
                        });
                });

            modelBuilder.Entity("AirportSystem.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedSeatID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PassengerID");

                    b.HasIndex("AssignedSeatID")
                        .IsUnique();

                    b.HasIndex("FlightID");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerID = 1,
                            AssignedSeatID = 1,
                            FlightID = 1,
                            FullName = "John Doe",
                            IsCheckedIn = true,
                            PassportNumber = "P1234567"
                        },
                        new
                        {
                            PassengerID = 2,
                            AssignedSeatID = 2,
                            FlightID = 1,
                            FullName = "Jane Smith",
                            IsCheckedIn = true,
                            PassportNumber = "P2345678"
                        },
                        new
                        {
                            PassengerID = 3,
                            FlightID = 2,
                            FullName = "Bob Johnson",
                            IsCheckedIn = false,
                            PassportNumber = "P3456789"
                        },
                        new
                        {
                            PassengerID = 4,
                            FlightID = 1,
                            FullName = "Alice Brown",
                            IsCheckedIn = false,
                            PassportNumber = "P4567890"
                        },
                        new
                        {
                            PassengerID = 5,
                            FlightID = 1,
                            FullName = "Charlie Wilson",
                            IsCheckedIn = false,
                            PassportNumber = "P5678901"
                        },
                        new
                        {
                            PassengerID = 6,
                            FlightID = 2,
                            FullName = "Diana Davis",
                            IsCheckedIn = false,
                            PassportNumber = "P6789012"
                        },
                        new
                        {
                            PassengerID = 7,
                            FlightID = 2,
                            FullName = "Eve Miller",
                            IsCheckedIn = false,
                            PassportNumber = "P7890123"
                        },
                        new
                        {
                            PassengerID = 8,
                            FlightID = 1,
                            FullName = "Frank Garcia",
                            IsCheckedIn = false,
                            PassportNumber = "P8901234"
                        });
                });

            modelBuilder.Entity("AirportSystem.Models.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassengerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("SeatID");

                    b.HasIndex("FlightID");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatID = 1,
                            FlightID = 1,
                            IsOccupied = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 2,
                            FlightID = 1,
                            IsOccupied = true,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 3,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 4,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            SeatID = 5,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            SeatID = 10,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            SeatID = 11,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            SeatID = 12,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            SeatID = 13,
                            FlightID = 1,
                            IsOccupied = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            SeatID = 6,
                            FlightID = 2,
                            IsOccupied = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 7,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 8,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 9,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            SeatID = 14,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            SeatID = 15,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            SeatID = 16,
                            FlightID = 2,
                            IsOccupied = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            SeatID = 17,
                            FlightID = 3,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 18,
                            FlightID = 3,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 19,
                            FlightID = 3,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 20,
                            FlightID = 3,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            SeatID = 21,
                            FlightID = 3,
                            IsOccupied = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            SeatID = 22,
                            FlightID = 4,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 23,
                            FlightID = 4,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 24,
                            FlightID = 4,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 25,
                            FlightID = 4,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            SeatID = 26,
                            FlightID = 5,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 27,
                            FlightID = 5,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 28,
                            FlightID = 5,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 29,
                            FlightID = 5,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            SeatID = 30,
                            FlightID = 6,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 31,
                            FlightID = 6,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 32,
                            FlightID = 6,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 33,
                            FlightID = 7,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 34,
                            FlightID = 7,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 35,
                            FlightID = 7,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 36,
                            FlightID = 8,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 37,
                            FlightID = 8,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 38,
                            FlightID = 8,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 39,
                            FlightID = 9,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 40,
                            FlightID = 9,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 41,
                            FlightID = 9,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            SeatID = 42,
                            FlightID = 10,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            SeatID = 43,
                            FlightID = 10,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            SeatID = 44,
                            FlightID = 10,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        });
                });

            modelBuilder.Entity("AirportSystem.Models.Passenger", b =>
                {
                    b.HasOne("AirportSystem.Models.Seat", "AssignedSeat")
                        .WithOne("Passenger")
                        .HasForeignKey("AirportSystem.Models.Passenger", "AssignedSeatID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AirportSystem.Models.Flight", "Flight")
                        .WithMany("Passengers")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSeat");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportSystem.Models.Seat", b =>
                {
                    b.HasOne("AirportSystem.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportSystem.Models.Flight", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("AirportSystem.Models.Seat", b =>
                {
                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
